#!/bin/sh
### BEGIN INIT INFO
# Provides:          summarizerd
# Required-Start:    $network $remote_fs $local_fs 
# Required-Stop:     $network $remote_fs $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Stop/start summarizerd
### END INIT INFO

# Author: Reetesh Ranjan

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC=summarizerd
NAME=summarizerd
DAEMON=/usr/local/summarizer/bin/$NAME
PIDFILE=/var/log/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

[ -x $DAEMON ] || exit 0

[ -r /etc/default/$NAME ] && . /etc/default/$NAME

DAEMON_ARGS="-v 5 -w 4"

. /lib/init/vars.sh

. /lib/lsb/init-functions

do_start()
{
    ulimit -c unlimited
    if [ ! -f $PIDFILE ]
    then
        $DAEMON $DAEMON_ARGS
        while [ ! -f $PIDFILE -o -z $PIDFILE ]
        do
            sleep 1
        done
        echo "$NAME started with pid $(cat $PIDFILE)"
    else
        found=`ps auxwww | awk '{print $2}' | grep -w $(cat $PIDFILE)`
        if [ "$found" = "" ]
        then
            $DAEMON $DAEMON_ARGS
        else
            echo "$NAME with pid $found already running..."
        fi
    fi
}

do_stop()
{
    # Return
    #   0 if daemon has been stopped
    #   1 if daemon was already stopped
    #   2 if daemon could not be stopped
    #   other if a failure occurred
    if [ -f $PIDFILE ]
    then
        found=`ps auxwww | awk '{print $2}' | grep -w $(cat $PIDFILE)`
        if [ "$found" != "" ]
        then
            kill -TERM `cat $PIDFILE`
        fi
        found=`ps auxwww | grep "$DAEMON $DAEMON_ARGS" | grep -v grep`
        while [ "$found" != "" ]
        do
            sleep 1
            found=`ps auxwww | grep "$DAEMON $DAEMON_ARGS" | grep -v grep`
        done
        echo "Existing $NAME processes stopped"
    else
        echo "No existing $NAME process found..."
    fi
}

case "$1" in
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    *)
        echo "Usage: $SCRIPTNAME {start|stop}" >&2
        exit 3
        ;;
esac

exit $RETVAL
